# Generated by Django 4.2.10 on 2024-07-31 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billformonth', models.DateField(default=django.utils.timezone.now)),
                ('currentreading', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('previousreading', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('totalunit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chargeperunit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('finalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duedate', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('total_bill_amt', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very Dissatisfied', 'Very Dissatisfied')], max_length=50)),
                ('ease_of_use', models.CharField(choices=[('Very Easy', 'Very Easy'), ('Easy', 'Easy'), ('Neutral', 'Neutral'), ('Difficult', 'Difficult'), ('Very Difficult', 'Very Difficult')], max_length=50)),
                ('features_like', models.TextField(blank=True, null=True)),
                ('additional_features', models.TextField(blank=True, null=True)),
                ('customer_support', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor'), ('Very Poor', 'Very Poor')], max_length=50)),
                ('billing_process', models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very Dissatisfied', 'Very Dissatisfied')], max_length=50)),
                ('improvement_suggestions', models.TextField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unitrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialunit', models.FloatField(default=0.0)),
                ('finalunit', models.FloatField(default=0.0)),
                ('unitrate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('connectionid', models.BigIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('connectiontype', models.CharField(max_length=100, null=True)),
                ('connectionstartdate', models.DateField(null=True)),
                ('occupation', models.CharField(max_length=100, null=True)),
                ('connectionload', models.CharField(max_length=100, null=True)),
                ('plotno', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('pincode', models.CharField(max_length=10, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.FloatField(default=0.0)),
                ('load_rate', models.FloatField(default=0.0)),
                ('load_rate_details', models.CharField(max_length=10, null=True)),
                ('load_amount', models.FloatField(default=0.0)),
                ('load_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_fppas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fppas', models.FloatField(default=0.0)),
                ('fppas_rate', models.FloatField(default=0.0)),
                ('fppas_rate_details', models.CharField(max_length=10, null=True)),
                ('fppas_amount', models.FloatField(default=0.0)),
                ('fppas_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.FloatField(default=0.0)),
                ('duty_rate', models.FloatField(default=0.0)),
                ('duty_rate_details', models.CharField(max_length=10, null=True)),
                ('duty_amount', models.FloatField(default=0.0)),
                ('duty_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_cess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cess', models.FloatField(default=0.0)),
                ('cess_rate', models.FloatField(default=0.0)),
                ('cess_rate_details', models.CharField(max_length=10, null=True)),
                ('cess_amount', models.FloatField(default=0.0)),
                ('cess_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_cal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=0.0)),
                ('rate_details', models.CharField(max_length=10, null=True)),
                ('amount', models.FloatField(default=0.0)),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electricity.connection'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('connection', 'billformonth')},
        ),
    ]
