# Generated by Django 4.2.10 on 2024-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electricity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='current_bill_images',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
